Repository google/closure-compiler, pull requests merged in 2021-05, with the labels that each got.

#3785 Add retrieval type enum to OriginalMappings
  src/com/google/debugging/sourcemap/SourceMapConsumerV3.java
  src/com/google/debugging/sourcemap/proto/mapping.proto
  test/com/google/debugging/sourcemap/SourceMapConsumerV3Test.java
  test/com/google/javascript/jscomp/CompilerTest.java
  test/com/google/javascript/jscomp/bundle/CoverageInstrumenterTest.java
Labels: cla: yes

#3801 Remove long deprecated CLI flags
  src/com/google/javascript/jscomp/CommandLineRunner.java
  test/com/google/javascript/jscomp/CommandLineRunnerTest.java
Labels: cla: yes, triage-done

#3804 IntersectionObserver constructor: support document root
  externs/browser/intersection_observer.js
Labels: cla: yes

#3815 Add missing extern for RegExp.prototype.dotAll
  externs/es3.js
Labels: cla: yes

#3816 Add missing extern for RegExp.prototype.unicode
  externs/es3.js
Labels: cla: yes

#3818 Add missing extern for Promise.any
  externs/es6.js
Labels: cla: yes

#3820 Use the normal type annotation for strings
  externs/es6.js
Labels: cla: yes

#3824 dead link to code_of_conduct.md file in README.md
  README.md
Labels: bug, cla: yes
